"""Create tables

Revision ID: 5fada68de757
Revises: 
Create Date: 2025-06-17 13:47:36.425209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fada68de757'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinician',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('registration_id', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id')
    )
    op.create_table('medication',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('code_name', sa.String(length=100), nullable=False),
    sa.Column('code_system', sa.String(length=100), nullable=False),
    sa.Column('strength_value', sa.Integer(), nullable=False),
    sa.Column('strength_unit', sa.String(length=50), nullable=False),
    sa.Column('form', sa.Enum('powder', 'tablet', 'capsule', 'syrup', name='medication_form_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', name='patient_sex_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_reference', sa.Integer(), nullable=False),
    sa.Column('clinician_reference', sa.String(length=20), nullable=False),
    sa.Column('medication_reference', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('prescribed_date', sa.Date(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'cancelled', 'on-hold', name='medication_request_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['clinician_reference'], ['clinician.registration_id'], ),
    sa.ForeignKeyConstraint(['medication_reference'], ['medication.code'], ),
    sa.ForeignKeyConstraint(['patient_reference'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medication_request')
    op.drop_table('patient')
    op.drop_table('medication')
    op.drop_table('clinician')
    # ### end Alembic commands ###
